PROGRAMS := device_c
#MOD_HEADERS := http_server.h dev_manager.h drivers.h device.h
#MOD_SOURCES := http_server.cpp dev_manager.cpp drivers.cpp device.cpp

#SIMPLE_TESTS := dev_manager driver_spp
#OTHER_TESTS := dev_server.test1\
#               dev_server.test2\
#               dev_server.test3

#PKG_CONFIG := libmicrohttpd
PKG_CONFIG := libcurl

MODDIR := ../modules
include $(MODDIR)/Makefile.inc




