PROGRAMS := dev_server
MOD_HEADERS := http_server.h device_manager.h driver.h mhd_locks.h locks.h
MOD_SOURCES := http_server.cpp device_manager.cpp

SIMPLE_TESTS := device_manager

PKG_CONFIG := libmicrohttpd

MODDIR := ../modules
include $(MODDIR)/Makefile.inc




