#!/bin/sh -efu

name=device2
ver=1.6
tag=
DIR="$name-$ver"

rm -rf -- "$DIR"
mkdir "$DIR"
cd "$DIR"

git clone ../../ .
[ ! -d modules ] || git submodule init
[ "$tag" = "" ]  || git checkout --detach $tag
[ ! -d modules ] || git submodule update

rm -rf .git .gear

mkdir debian
for f in changelog control copyright rules; do
  sed 's/${ver}/'$ver'/g' ../$f > debian/$f
done

dpkg-buildpackage --build=any

cd ..
rm -rf -- "$DIR"
